import Header from "@/components/header/Header";
import { raleway } from "@/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fabryka Sypialni",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <head>
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={`bg-gray-100 ${raleway.className}`}>
        <Header />
        {children}

        <div className="z-10 h-[200vh] w-full bg-white" />
      </body>
    </html>
  );
}
